title: "my blog1"
date: 2019-04-07
author: doktorgee
email: stephenbgilson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An awesome description for my new site

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
